name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast-analysis:
    name: SAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SAST with Syhunt (manual)
        run: |
          echo "⚠️ Syhunt deve ser executado manualmente fora do GitHub (Windows only)"

  dast-analysis:
    name: DAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Application (Simulado)
        run: |
          echo "⚠️ Rode seu app aqui em segundo plano (ex: node app.js &)"

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://juice-shop.herokuapp.com'
          artifact-name: zap_scan_report
